# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# Для подсказок в коде использовать CTRL + SPACE

name: .NET

on: [push, pull_request]

jobs:
  build:
    name: Initialize build on .NET Core
    
    runs-on: windows-latest

    steps:
    # Выгрузка репозитория Github Actions в ОС
    - uses: actions/checkout@v4
    # Подключения механизмов компиляции .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    # Восстановление зависимостей
    - name: Restore dependencies
      run: dotnet restore
    # Сборка
    - name: Build
      run: dotnet build --no-restore
    # Запуск тестов
    - name: Test
      run: dotnet test --no-build --verbosity normal
